src/main/java/seedu/address/model/UserPrefs.java, src/main/java/seedu/address/ui/MainWindow.java
This changes the default size of the GUI to 800*600 which is consistant with the prototype GUI size.
=> To change default size of GUI to 800*600

src/main/java/seedu/address/model/task/Deadline.java, src/main/java/seedu/address/model/task/Event.java
=> Refine task child classes

docs/UserGuide.md
=> Updated userguide: Added undo command

src/main/java/seedu/address/commons/exceptions/IncorrectCommandException.java, src/main/java/seedu/address/logic/commands/AddCommand.java, src/main/java/seedu/address/logic/parser/ArgumentsParser.java, src/main/java/seedu/address/logic/parser/CommandArgs.java, src/main/java/seedu/address/logic/parser/Parser.java, src/test/java/seedu/address/logic/LogicManagerTest.java, src/test/java/seedu/address/testutil/TestTask.java
=> The great Parser overhaul

src/main/java/seedu/address/logic/parser/ArgumentsParser.java
Fixes a bug where the parser would throw invalid command exception even if all required arguments is present
=> A simple bug fix

src/main/java/seedu/address/commons/core/Messages.java, src/main/java/seedu/address/logic/commands/AddCommand.java, src/main/java/seedu/address/logic/parser/Parser.java, src/test/java/seedu/address/logic/LogicManagerTest.java
=> Modify add command to include event and deadline (pre-natty)

src/main/java/seedu/address/commons/events/model/TaskForceCommandExecutedEvent.java, src/main/java/seedu/address/logic/LogicManager.java, src/main/java/seedu/address/model/Model.java, src/main/java/seedu/address/model/ModelManager.java
This event will fire after a command is executed and it contains the user input, the command class and its result.
This is a required event for the undo command
=> To add a new event: TaskForceCommandExecutedEvent

src/main/java/seedu/address/ui/TaskCard.java, src/main/java/seedu/address/ui/TaskListPanel.java, src/main/resources/view/DarkTheme.css, src/main/resources/view/MainWindow.fxml, src/main/resources/view/TaskListCard.fxml
WIP
current bugs:
dates disappear from label when program are rerun.
=> Refine UI to display basic dates for deadline and event

src/main/java/seedu/address/logic/parser/ArgumentsParser.java, src/test/java/seedu/address/logic/LogicManagerTest.java
@tanboonjoon 
The argument parser will now only add what it needs when the flags are added, allowing the same flags identifier to be reused in different commands and context
=> Fixes argument parser

src/main/java/seedu/address/logic/commands/AddCommand.java, src/main/java/seedu/address/logic/commands/EditCommand.java
=> Added command aliases for add and edit command

src/main/java/seedu/address/commons/events/model/TaskForceTaskListChangedEvent.java, src/main/java/seedu/address/model/task/UniqueTaskList.java, src/main/java/seedu/address/ui/ResultDisplay.java, src/main/java/seedu/address/ui/TaskCard.java, src/main/java/seedu/address/ui/TaskListPanel.java, src/main/java/seedu/address/ui/UiManager.java, src/main/resources/view/DarkTheme.css, src/main/resources/view/TaskListCard.fxml
- The UI will now scroll down to the latest task added/removed by user.
=> Small UI improvements

src/main/java/seedu/address/logic/commands/FindCommand.java, src/main/java/seedu/address/logic/parser/FindCommandParser.java, src/main/java/seedu/address/model/ModelManager.java, src/test/java/guitests/FindCommandTest.java
=> FindCommand bug fix/refactoring

src/main/java/seedu/address/logic/commands/DeleteCommand.java, src/main/java/seedu/address/logic/parser/DeleteCommandParser.java, src/main/resources/view/TaskListCard.fxml, src/test/java/guitests/DeleteCommandTest.java, src/test/java/seedu/address/logic/LogicManagerTest.java
References #81 
To delete multiple tasks, seperate their ids with commans 
**Examples**
---
> delete 1,2, 3 <br>
Deletes tasks with indexes 1, 2 and 3
> delete 1,2, not a number <br>
Invalid command exception
> delete 1,2, 1000000 <br>
Deletes tasks 1, 2 and ignores 1000000
=> Enchanced delete command

src/main/java/seedu/address/commons/core/Config.java, src/main/java/seedu/address/logic/LogicManager.java, src/main/java/seedu/address/logic/commands/FindCommand.java, src/main/java/seedu/address/logic/parser/FindCommandParser.java, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/model/TaskForce.java
Find command to filter out startDate
some refactoring
some removal of import library that are not used in the code
reference #80
=> Find command to filter out startDate

src/main/java/seedu/address/logic/commands/CdCommand.java, src/main/java/seedu/address/logic/commands/FindCommand.java, src/main/java/seedu/address/logic/parser/CdCommandParser.java, src/main/java/seedu/address/logic/parser/FindCommandParser.java, src/main/java/seedu/address/model/ModelManager.java, src/test/java/guitests/FindCommandTest.java
=> Fix find command to filter all the event in that particular week

build.gradle
=> Adds the Aho-Corasick algorithm library as a dependency

forDemoUse.xml, src/main/java/seedu/address/model/ModelManager.java
=> use aho corasik for find all

src/main/java/seedu/address/logic/filters/Expression.java, src/main/java/seedu/address/logic/filters/NameQualifier.java, src/main/java/seedu/address/logic/filters/PredicateExpression.java, src/main/java/seedu/address/logic/filters/Qualifier.java, src/main/java/seedu/address/logic/filters/TaskIdentifierNumberQualifier.java, src/main/java/seedu/address/model/Model.java, src/main/java/seedu/address/model/ModelManager.java
=> Seperates name qualifer to seperate files

src/main/java/seedu/address/logic/commands/AddCommand.java, src/main/java/seedu/address/logic/commands/BlockCommand.java, src/main/java/seedu/address/logic/parser/BlockCommandParser.java, src/main/java/seedu/address/logic/parser/Parser.java, src/main/java/seedu/address/model/task/Block.java, src/test/java/guitests/BlockCommandTest.java, src/test/java/seedu/address/logic/LogicManagerTest.java
=> Block command

src/main/java/seedu/address/logic/commands/ConfirmCommand.java, src/main/java/seedu/address/logic/parser/CommandArgs.java, src/main/java/seedu/address/logic/parser/ConfirmCommandParser.java, src/main/java/seedu/address/logic/parser/Parser.java, src/main/java/seedu/address/model/TaskForce.java, src/main/java/seedu/address/storage/XmlAdaptedTask.java, src/test/java/guitests/ConfirmCommandTest.java
=> Implements confirm command

src/main/java/seedu/address/logic/commands/AddCommand.java, src/main/java/seedu/address/logic/commands/BlockCommand.java, src/main/java/seedu/address/logic/commands/ConfirmCommand.java, src/main/java/seedu/address/logic/commands/FreetimeCommand.java, src/main/java/seedu/address/logic/filters/Expression.java, src/main/java/seedu/address/logic/filters/NameQualifier.java, src/main/java/seedu/address/logic/filters/PredicateExpression.java, src/main/java/seedu/address/logic/filters/Qualifier.java, src/main/java/seedu/address/logic/filters/TaskIdentifierNumberQualifier.java, src/main/java/seedu/address/logic/parser/BlockCommandParser.java, src/main/java/seedu/address/logic/parser/CommandArgs.java, src/main/java/seedu/address/logic/parser/ConfirmCommandParser.java, src/main/java/seedu/address/logic/parser/FreetimeCommandParser.java, src/main/java/seedu/address/logic/parser/Parser.java, src/main/java/seedu/address/model/Model.java, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/model/TaskForce.java, src/main/java/seedu/address/model/task/Block.java, src/main/java/seedu/address/storage/XmlAdaptedTask.java, src/test/java/guitests/BlockCommandTest.java, src/test/java/guitests/CdCommandTest.java, src/test/java/guitests/ConfirmCommandTest.java, src/test/java/guitests/FreetimeTest.java, src/test/java/guitests/forTesting.xml, src/test/java/seedu/address/logic/LogicManagerTest.java
WIP
Left:
Refactoring and removing all the brute force String msg
test case,
testing
=> Freetime command

src/main/java/seedu/address/logic/commands/FreetimeCommand.java, src/main/java/seedu/address/logic/filters/NameQualifier.java, src/test/java/guitests/FreetimeTest.java
make find command can filter out ongoing event
make freetime command to consider ongoing event as well
=> make find filter out ongoing event

src/main/java/seedu/address/commons/core/Messages.java, src/main/java/seedu/address/commons/events/model/TaskForceCommandExecutedEvent.java, src/main/java/seedu/address/commons/util/DateUtil.java, src/main/java/seedu/address/logic/LogicManager.java, src/main/java/seedu/address/logic/commands/AddCommand.java, src/main/java/seedu/address/logic/commands/ConfirmCommand.java, src/main/java/seedu/address/logic/filters/AlwaysTrueQualifier.java, src/main/java/seedu/address/logic/filters/NameQualifier.java, src/main/java/seedu/address/logic/parser/DeleteCommandParser.java, src/main/java/seedu/address/model/Model.java, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/storage/XmlAdaptedTask.java, src/test/java/guitests/AddCommandTest.java, src/test/java/guitests/FindCommandTest.java, src/test/java/seedu/address/logic/ArgsParserTest.java, src/test/java/seedu/address/logic/LogicManagerTest.java
=> Implemented event conflict detection

src/main/java/seedu/address/commons/events/model/TaskForceTaskListChangedEvent.java, src/main/java/seedu/address/ui/TaskListPanel.java, src/main/java/seedu/address/ui/UiManager.java
instead of the index which might not be the last index in a sorted list
=> Changed the list change event to instead pass the Task object added

src/main/java/seedu/address/MainApp.java, src/main/java/seedu/address/commons/core/Config.java, src/main/java/seedu/address/commons/events/model/TaskForceTaskListChangedEvent.java, src/main/java/seedu/address/commons/util/ConfigUtil.java, src/main/java/seedu/address/commons/util/JsonUtil.java, src/main/java/seedu/address/logic/LogicManager.java, src/main/java/seedu/address/logic/commands/CdCommand.java, src/main/java/seedu/address/model/Model.java, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/ui/TaskListPanel.java, src/main/java/seedu/address/ui/UiManager.java, src/test/data/ConfigUtilTest/ExtraValuesConfig.json, src/test/data/ConfigUtilTest/TypicalConfig.json, src/test/java/guitests/CdCommandTest.java, src/test/java/guitests/FindCommandTest.java, src/test/java/seedu/address/commons/core/ConfigTest.java, src/test/java/seedu/address/commons/util/ConfigUtilTest.java
This PR hopes to make adding in new configuration options less clunky.
=> The configuration overhaul attempt number 2

src/main/java/seedu/address/logic/commands/FreetimeCommand.java, src/main/java/seedu/address/logic/parser/FreetimeCommandParser.java, src/test/java/guitests/FindCommandTest.java, src/test/java/guitests/FreetimeTest.java
=> Freetime improvement

src/main/java/seedu/address/commons/core/Config.java
value if for some reason the key is tampered with
=> The config class now stores default values and returns the default

src/main/java/seedu/address/commons/util/DateUtil.java, src/main/java/seedu/address/logic/commands/AddCommand.java, src/main/java/seedu/address/logic/commands/ConfirmCommand.java, src/main/java/seedu/address/logic/commands/EditCommand.java, src/main/java/seedu/address/logic/parser/BlockCommandParser.java, src/main/java/seedu/address/model/Model.java, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/model/TaskForce.java, src/main/java/seedu/address/model/tag/ReadOnlyTagRegistrar.java, src/main/java/seedu/address/model/tag/Tag.java, src/main/java/seedu/address/model/tag/TagRegistrar.java, src/test/java/seedu/address/commons/core/TagRegistryTest.java, src/test/java/seedu/address/logic/LogicManagerTest.java
=> Tagging system overhaul

src/main/java/seedu/address/commons/core/Config.java, src/main/java/seedu/address/logic/commands/ClearCommand.java, src/main/java/seedu/address/logic/commands/ConfigCommand.java, src/main/java/seedu/address/logic/parser/CommandArgs.java, src/main/java/seedu/address/logic/parser/ConfigCommandParser.java, src/main/java/seedu/address/logic/parser/Parser.java, src/test/java/guitests/ConfigCommandTest.java, src/test/java/seedu/address/TestApp.java, src/test/java/seedu/address/logic/LogicManagerTest.java
=> Added config command and a new config option

docs/DeveloperGuide.md, docs/UserGuide.md, src/main/java/seedu/address/logic/commands/ClearCommand.java, src/main/java/seedu/address/model/ModelManager.java
Reverts CS2103AUG2016-F10-C2/main#174
=> Revert "implement confirmation dialog for clear command"

collated/docs/A0111277M.md, collated/docs/A0139942W.md, collated/docs/A0140037W.md, collated/main/A0111277M.md, collated/main/A0135768R.md, collated/main/A0139942W.md, collated/main/A0140037W.md, collated/test/A0135768R.md, collated/test/A0139942W.md, collated/test/A0140037W.md, docs/DeveloperGuide.md, docs/UserGuide.md, src/main/java/seedu/address/logic/commands/FindCommand.java, src/main/java/seedu/address/logic/filters/NameQualifier.java, src/main/java/seedu/address/logic/parser/CommandArgs.java, src/main/java/seedu/address/logic/parser/FindCommandParser.java, src/test/java/guitests/FindCommandTest.java
=> improve findCommand

src/main/java/seedu/address/logic/commands/CdCommand.java, src/main/java/seedu/address/logic/commands/FreetimeCommand.java, src/main/java/seedu/address/logic/filters/NameQualifier.java, src/main/java/seedu/address/logic/parser/CdCommandParser.java, src/main/java/seedu/address/logic/parser/FindCommandParser.java, src/main/java/seedu/address/logic/parser/FreetimeCommandParser.java, src/test/java/guitests/FreetimeTest.java
Agende for this pullrequest : 
reference #203
=> fix bug and refactoring stage 1

src/main/java/seedu/address/ui/CommandBox.java
=> Fixed undo status message not showing.

src/test/java/guitests/FindCommandTest.java, src/test/java/guitests/FreetimeTest.java, src/test/java/guitests/TaskForceGuiTest.java
=> assertListSize method to include EventListPanel

src/main/java/seedu/address/logic/commands/FindCommand.java, src/main/java/seedu/address/logic/commands/FreetimeCommand.java, src/main/java/seedu/address/logic/filters/NameQualifier.java, src/main/java/seedu/address/logic/parser/FindCommandParser.java, src/test/java/guitests/FreetimeTest.java
=> check activehour for freetime

collated/main/A0140037W.md, collated/test/A0140037W.md, src/main/java/seedu/address/logic/commands/EditCommand.java, src/main/java/seedu/address/logic/parser/EditCommandParser.java, src/main/java/seedu/address/logic/parser/RedoCommandParser.java, src/main/java/seedu/address/logic/parser/UndoCommandParser.java, src/test/java/guitests/EditCommandTest.java, src/test/java/guitests/UndoAndRedoCommandTest.java, src/test/java/guitests/guihandles/CommandBoxHandle.java
If happy and no break can click merge.
=> Final check and collate.
